name: socket_io_server
description: Port of JS/Node library Socket.io. It enables real-time, bidirectional and 
  event-based communication cross-platform.
version: 0.0.1
# repository: https://github.com/my_org/my_repo //TODO

environment:
  sdk: ^3.3.4

# Add regular dependencies here.
dependencies:
  socket_io_common: ^2.0.3
  uuid: ^4.4.0
  stream: ^3.2.3
  logging: ^1.2.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
